#!/usr/bin/env bash

case "$1" in
    "s", "setup")
    (
        scripts/setup.sh $2 || exit 1
    )
    ;;
    "g" | "generate" | "gen")
    (
        scripts/generate.sh $2 || exit 1
    )
    ;;
    *)
    (
        echo "MCP-Patcher CLI Tool"
        echo ""
        echo "A variety of commands to assist you in managing patches."
        echo "You can find a list of commands below."
        echo ""
        echo " Commands:"
        echo "  * s, setup          | Setup MCP-Reborn."
        echo "  * g, generate, gen  | Generate all patches."
        echo "  * p, patch          | Apply all patches to the project."
    )
    ;;
esac
